<?php
// Define routes as an associative array
$routes = [
    // Add more routes here as needed
    '' => ['controller' => 'HomeController', 'action' => 'index'],
    'news' => ['controller' => 'NewsController', 'action' => 'news'],
    'news/detail' => ['controller' => 'NewsController', 'action' => 'detail'],
    'login' => ['controller' => 'LoginController', 'action' => 'show'],
    'login/submit' => ['controller' => 'LoginController', 'action' => 'login'],
    'register' => ['controller' => 'RegisterController', 'action' => 'show'],
    'register/submit' => ['controller' => 'RegisterController', 'action' => 'register'],
    'orderhistory' => ['controller' => 'OrderHistoryController', 'action' => 'order_history'],
    'logout' => ['controller' => 'LoginController', 'action' => 'logout'],
    'product_list' => ['controller' => 'CustomerProductController', 'action' => 'products'],
    'product_list/detail' => ['controller' => 'CustomerProductController', 'action' => 'detail'],
    'detail/submit' => ['controller' => 'CustomerProductController', 'action' => 'addToCart'],
    'cart' => ['controller' => 'CartController', 'action' => 'showcart'],
    'deleteItem/submit' => ['controller' => 'CartController', 'action' => 'delete'],
    'promotionApply/submit' => ['controller' => 'CartController', 'action' => 'promotionApply'],
    'info' => ['controller' => 'InfoController', 'action' => 'info'],
    'info/submit' => ['controller' => 'InfoController', 'action' => 'updateinfo'],
    'payment' => ['controller' => 'PaymentController', 'action' => 'getall'],
    'payment/updatedefaultcard' => ['controller' => 'PaymentController', 'action' => 'updatedefaultcard'],
    'payment/updatedefaultbank' => ['controller' => 'PaymentController', 'action' => 'updatedefaultbank'],
    'payment/deletecard' => ['controller' => 'PaymentController', 'action' => 'deleteCard'],
    'payment/deletebank' => ['controller' => 'PaymentController', 'action' => 'deleteBank'],
    'dashboard' => ['controller' => 'DashBoardController', 'action' => 'getall'],
    'order' => ['controller' => 'OrderController', 'action' => 'order'],
    'order/detail' => ['controller' => 'OrderController', 'action' => 'detail'],
    'customers' => ['controller' => 'CustomerController', 'action' => 'customers'],
    'products' => ['controller' => 'ProductController', 'action' => 'products'],
    'addproduct' => ['controller' => 'ProductController', 'action' => 'show'],
    'addproduct/submit' => ['controller' => 'ProductController', 'action' => 'addproduct'],
    'products/updateproduct' => ['controller' => 'ProductController', 'action' => 'showupdate'],
    'updateproduct/submit' => ['controller' => 'ProductController', 'action' => 'updateproduct'],
    'products/deleteproduct' => ['controller' => 'ProductController', 'action' => 'showdelete'],
    'deleteproduct/submit' => ['controller' => 'ProductController', 'action' => 'deleteproduct'],
];

